### ISSUE TITLE
Failed integration in version 2023.3

### ISSUE THREAD

**Issue by edudele** [dmamontov/hass-miwifi#115]
**Describe the bug**

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 09:08:54 (1 occurrences)
Last logged: 09:08:54

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for miwifi using this method at custom_components/miwifi/__init__.py, line 100: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Please complete the following information:**
 - HASS version: 2023.2.1
 - Component version v2.9.0
 - Router model AX3600
 - Router firmware version 3.0.22 EU

**Comment by Cigareoc** [comment]
Good evening! I have same error
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for miwifi using this method at custom_components/miwifi/__init__.py, line 100: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AX3600

**Comment by dmamontov** [comment]
Fixed in release https://github.com/dmamontov/hass-miwifi/releases/tag/v3.0.0

@edudele thanks.
